[[redirects]]
  from = "/netplot-Sunbelt2023"
  to = "https://UofUEpiBio.github.io/netplot-subelt2023"
  status = 301
  force = true
[[redirects]]
  from = "/epiworldR-workshop"
  to = "https://UofUEpiBio.github.io/epiworldR-workshop"
  status = 301
  force = true
[[redirects]]
  from = "/slides/image-retreat2023"
  to = "https://gvegayon.github.io/image-retreat2023/"
  status = 301
  force = true
[[redirects]]
  from = "/slides/uou-cdc-june2023"
  to = "https://docs.google.com/presentation/d/14eP8lFgRrExTgU3D1uvbL-gu7YuX7dKHoUIV1mgWf5U/edit?usp=sharing"
  status = 301
  force = true
[[redirects]]
  from = "/slides/mind2023"
  to = "https://gvegayon.github.io/mech-ml-mind/"
  status = 301
  force = true
[[redirects]]
  from = "/image2023"
  to = "https://github.com/gvegayon/image2023/blob/master/slides.pdf"
  status = 301
  force = true
[[redirects]]
  from = "/slides/sci2023"
  to = "https://github.com/gvegayon/sci2023"
  status = 301
  force = true
[[redirects]]
  from = "/UoUDS2023"
  to = "https://github.com/gvegayon/talks/tree/master/20230111-uofu-datascience"
  status = 301
  force = true
[[redirects]]
  from = "/quinlanlab2022"
  to = "https://github.com/gvegayon/talks/tree/master/20221208-quinlan-lab"
  status = 301
  force = true
[[redirects]]
  from = "/spur2023"
  to = "https://our.utah.edu/spur/visualization-tools-for-network-science-building-beautiful-graphs-with-netplot/"
  status = 301
  force = true
[[redirects]]
  from = "/sunbelt2022"
  to = "https://github.com/gvegayon/gallery/tree/master/20220700-sunbelt"
  status = 301
  force = true
[[redirects]]
  from = "/slides/happiest"
  to = "https://docs.google.com/presentation/d/1koWJnekIcQyPbHGSrq0lBp0doZTKQK309H7xHgeHilY/edit?usp=sharing"
  status = 301
  force = true
[[redirects]]
  from = "/apps/epiworld"
  to = "https://github.com/UofUEpi/epiworld"
  status = 301
  force = true
[[redirects]]
  from = "/slides/epiworld1/"
  to = "https://docs.google.com/presentation/d/1chntyM9itTJv9lm_urMa8cnSN-vgL1uOmNxPhvXrQFo/edit?usp=sharing"
  status = 301
  force = true
[[redirects]]
  from = "/slides/epiworld0/"
  to = "https://docs.google.com/presentation/d/183icOxjgGRJeyzf7QRCTglfhbjy_U7h8mO7V17OvSw4/edit?usp=sharing"
  status = 301
  force = true
[[redirects]]
  from = "/slides/netsnau0/"
  to = "https://github.com/gvegayon/netsnau0apr2022/raw/main/main.pdf"
  status = 301
  force = true
[[redirects]]
  from = "/slides/ars2021/"
  to = "https://github.com/gvegayon/ars2021/raw/master/slides.pdf"
  status = 301
  force = true
[[redirects]]
  from = "/slides/networks2021/"
  to = "https://github.com/gvegayon/networks2021/raw/master/handout.pdf"
  status = 301
  force = true
[[redirects]]
  from = "/slides/utah-epi/"
  to = "https://github.com/gvegayon/faculty-talk/raw/utah-epi/handout.pdf"
  status = 301
  force = true
[[redirects]]
  from = "/slides/nygc/"
  to = "https://github.com/gvegayon/ny-genome-talk/raw/nygc/handout.pdf"
  status = 301
  force = true
[[redirects]]
  from = "/slides/uai-fic/"
  to = "https://github.com/gvegayon/faculty-talk/raw/uai-fic/handout.pdf"
  status = 301
  force = true
[[redirects]]
  from = "/slides/uai-ds-may"
  to = "https://github.com/gvegayon/usc-biostats-seminar-may2021/tree/036a2019cfa687c12f9d496d3180ca9e28cd9719"
  status = 301
  force = true
[[redirects]]
  from = "/talk/*"
  to = "https://github.com/gvegayon/talks/blob/master/README.md"
  status = 301
  force = true
[[redirects]]
  from = "/publication/*"
  to   = "https://scholar.google.com/citations?user=34E1yTAAAAAJ&hl=en"
  status = 301
  force = true
[[redirects]]
  from = "/talks/*"
  to = "https://github.com/gvegayon/talks/blob/master/README.md"
  status = 301
  force = true
[[redirects]]
  from = "/papers/*"
  to   = "https://scholar.google.com/citations?user=34E1yTAAAAAJ&hl=en"
  status = 301
  force = true
[[redirects]]
  from   = "/meetme/*"
  to     = "https://calendar.app.google/LxNeGy5CtzaDroFv6"
  status = 301
  force  = true
