[[redirects]]
  from = "/slides/nygc/"
  to = "https://github.com/gvegayon/ny-genome-talk/raw/nygc/handout.pdf"
  status = 301
  force = true
[[redirects]]
  from = "/slides/uai-fic/"
  to = "https://github.com/gvegayon/faculty-talk/raw/uai-fic/handout.pdf"
  status = 301
  force = true
[[redirects]]
  from = "/talk/*"
  to = "https://github.com/gvegayon/talks/blob/master/README.md"
  status = 301
  force = true
[[redirects]]
  from = "/publication/*"
  to   = "https://scholar.google.com/citations?user=34E1yTAAAAAJ&hl=en"
  status = 301
  force = true
[[redirects]]
  from = "/talks/*"
  to = "https://github.com/gvegayon/talks/blob/master/README.md"
  status = 301
  force = true
[[redirects]]
  from = "/papers/*"
  to   = "https://scholar.google.com/citations?user=34E1yTAAAAAJ&hl=en"
  status = 301
  force = true
[[redirects]]
  from   = "/officehours/*"
  to     = "https://calendar.google.com/calendar/selfsched?sstoken=UU5Ra3M2QzFUeHNNfGRlZmF1bHR8OWI0ZjI1NTUxOWNlZjM2YTM4ZmViMmE2OWFlY2JjNWY"
  status = 301
  force  = true
