[[redirects]]
  from = "/talk/*"
  to = "https://github.com/gvegayon/talks/blob/master/README.md"
  status = 301
  force = true
[[redirects]]
  from = "/publication/*"
  to   = "https://scholar.google.com/citations?user=34E1yTAAAAAJ&hl=en"
  status = 301
  force = true
[[redirects]]
  from = "/talks/*"
  to = "https://github.com/gvegayon/talks/blob/master/README.md"
  status = 301
  force = true
[[redirects]]
  from = "/papers/*"
  to   = "https://scholar.google.com/citations?user=34E1yTAAAAAJ&hl=en"
  status = 301
  force = true
[[redirects]]
  from   = "/officehours/"
  tp     = "https://calendar.google.com/calendar/selfsched?sstoken=UU5Ra3M2QzFUeHNNfGRlZmF1bHR8OWI0ZjI1NTUxOWNlZjM2YTM4ZmViMmE2OWFlY2JjNWY"
  status = 301
  force  = true
