[[redirects]]
  from = "/talk/*"
  to = "https://github.com/gvegayon/talks/blob/master/README.md"
  status = 301
  force = true
[[redirects]]
  from = "/publication/*"
  to   = "https://scholar.google.com/citations?user=34E1yTAAAAAJ&hl=en"
  status = 301
  force = true

