[talk-1-conference]
entrytype = 'inproceedings'
title = 'Just tired of endless loops! or parallel: Stata module for parallel computing'
author = 'Vega Yon, George G.'
year = '2013'
month = '7'
date = '2013-07-18'
eventtitle = 'Stata Conference, 2013'
eventurl = 'https://www.stata.com/meeting/new-orleans13/'
host = 'Stata'
location = 'New Orleans, LA'
talktype = 'conference talk'
slides = 'https://github.com/gvegayon/talks/raw/master/20130718-parallel-stataconf/vega.pdf'
repo = 'https://ideas.repec.org/p/boc/norl13/4.html'
keywords = ['conferencetalk']
source = '20130718-parallel-stataconf'

[talk-2-conference]
entrytype = 'inproceedings'
title = 'Understanding Diffusion with netdiffuseR'
author = 'Vega Yon, George G.; Valente, Thomas W.'
year = '2016'
month = '3'
date = '2016-03-28'
eventtitle = 'Sunbelt Conference, 2016'
host = 'INSNA'
location = 'New Port Beach, CA'
talktype = 'conference workshop'
slides = 'https://github.com/USCCANA/netdiffuser-sunbelt2016'
video = 'https://www.youtube.com/playlist?list=PLT-GgRN1lFI4coHDqkRJm3flDw9e1gg2P'
repo = 'https://github.com/USCCANA/netdiffuser-sunbelt2016'
keywords = ['conferencetalk']
source = '20160328-sunbelt2016'

[talk-3-conference]
entrytype = 'inproceedings'
title = 'Network Diffusion of Innovations in R: Introducing netdiffuseR'
author = 'Vega Yon, George G.; Valente, Thomas W.'
year = '2016'
month = '6'
date = '2016-06-24'
eventtitle = 'IC2S2, 2016'
eventurl = 'https://www.kellogg.northwestern.edu/news-events/conference/ic2s2/2016.aspx'
host = 'Kellogg, NU'
location = 'Evanston, IL'
talktype = 'conference poster'
slides = 'https://github.com/USCCANA/netdiffuser-ic2s22016/raw/master/netdiffuseR_ic2s22016.pdf'
repo = 'https://github.com/USCCANA/netdiffuser-ic2s22016/'
keywords = ['conferencetalk']
source = '20160626-ic2s22016'

[talk-4-conference]
entrytype = 'inproceedings'
title = 'Network Diffusion of Innovations in R: Introducing netdiffuseR'
author = 'Vega Yon, George G.; Valente, Thomas W.'
year = '2016'
month = '6'
date = '2016-06-29'
eventtitle = 'useR! 2016'
host = 'Stanford University'
location = 'Stanford, CA'
talktype = 'conference talk'
slides = 'https://github.com/gvegayon/netdiffuser-user2016/raw/master/netdiffuseR_useR2016.pdf'
video = 'https://channel9.msdn.com/Events/useR-international-R-User-conference/useR2016/Network-Diffusion-of-Innovations-in-R-Introducing-netdiffuseR'
repo = 'https://github.com/gvegayon/netdiffuser-user2016'
keywords = ['conferencetalk']
source = '20160629-user2016'

[talk-5-conference]
entrytype = 'inproceedings'
title = 'Uncomplicated Parallel Computing with Stata'
author = 'Vega Yon, George G.; Quistorff, Brian'
year = '2017'
month = '7'
date = '2017-07-28'
eventtitle = 'Stata Conference 2017'
eventurl = 'https://www.stata.com/meeting/baltimore17/'
host = 'Stata'
location = 'Baltimore, MD'
talktype = 'conference talk'
slides = 'https://github.com/gvegayon/parallel/raw/master/talks/20170727_stata_conference/20170727_stata_conference.pdf'
repo = 'https://github.com/gvegayon/parallel/tree/master/talks/20170727_stata_conference'
speaker = 'Quistorff, Brian'
keywords = ['conferencetalk']
source = '20170700-stataconf'

[talk-6-conference]
entrytype = 'inproceedings'
title = 'Understanding Diffusion with netdiffuseR'
author = 'Vega Yon, George G.; Valente, Thomas W.'
year = '2017'
month = '7'
date = '2017-07-26'
eventtitle = 'NASN 2017'
eventurl = 'http://nasn2017.insna.org/'
host = 'INSNA'
location = 'Washington DC'
talktype = 'conference workshop'
slides = 'https://usccana.github.io/netdiffuser-nasn2017/'
repo = 'https://github.com/USCCANA/netdiffuser-nasn2017/'
keywords = ['conferencetalk']
source = '20170726-nasn2017'

[talk-7-conference]
entrytype = 'inproceedings'
title = 'Diffusion of Smoking Initiation Among Diverse, Urban American Adolescents Over The High School Period'
author = 'Vega Yon, George G.; de la Haye, Kayla; Shin, Hee-sung; Valente, Thomas'
year = '2017'
month = '7'
date = '2017-07-28'
eventtitle = 'NASN 2017'
eventurl = 'http://nasn2017.insna.org/'
host = 'INSNA'
location = 'Washington DC'
talktype = 'conference talk'
slides = 'https://github.com/gvegayon/talks/raw/master/20170728-nasn2017/sns_nasn2017.pdf'
repo = 'https://github.com/USCCANA/netdiffuser-nasn2017/'
keywords = ['conferencetalk']
source = '20170728-nasn2017'

[talk-8-conference]
entrytype = 'inproceedings'
title = 'Big Problems for Small Networks: Small Network Statistics'
author = 'Vega Yon, George G.; de la Haye, Kayla'
year = '2018'
month = '11'
date = '2018-11-28'
eventtitle = 'NASN 2018, DC'
eventurl = 'http://nasn2018.insna.org/'
host = 'INSNA'
location = 'Washington DC'
talktype = 'conference talk'
slides = 'https://github.com/muriteams/nasn2018/blob/nasn2018/index.pdf'
repo = 'https://github.com/muriteams/nasn2018/tree/nasn2018'
keywords = ['conferencetalk']
source = '20181129-nasn2018'

[talk-9-conference]
entrytype = 'inproceedings'
title = 'Small network statistics for the network science of teams'
author = 'Vega Yon, George G.; de la Haye, Kayla'
year = '2019'
month = '1'
date = '2019-01-03'
eventtitle = 'NetSciX 2019, SCL'
host = 'PUC'
location = 'Santiago, Chile'
talktype = 'conference talk'
slides = 'https://github.com/muriteams/nasn2018/raw/netscix2019/index.pdf'
repo = 'https://github.com/muriteams/nasn2018/tree/netscix2019'
keywords = ['conferencetalk']
source = '20190103-netscix2019'

[talk-10-conference]
entrytype = 'inproceedings'
title = 'Computacion de Alto Rendimiento con R'
author = 'Vega Yon, George G.'
year = '2018'
month = '12'
date = '2018-12-12'
eventtitle = 'satRday Santiago 2018'
eventurl = 'https://santiago2018.satrdays.org/'
location = 'Santiago, Chile'
talktype = 'conference workshop'
slides = 'https://github.com/gvegayon/satRdaySCL2018'
repo = 'https://github.com/gvegayon/satRdaySCL2018'
keywords = ['conferencetalk']
source = '20190104-satRdaySCL2018'

[talk-11-conference]
entrytype = 'inproceedings'
title = 'Exact Statistics and Semi-Parametric Tests for Small Network Data'
author = 'Vega Yon, George G.; Slaughter, Andrew; de la Haye, Kayla'
year = '2019'
month = '6'
date = '2019-06-20'
eventtitle = 'Sunbelt 2019'
eventurl = 'https://www.fourwav.es/view/717/info/'
host = 'INSNA'
location = 'Montreal, CA'
talktype = 'conference talk'
slides = 'https://github.com/gvegayon/sunbelt2019/blob/master/index-handout.pdf'
repo = 'https://github.com/gvegayon/sunbelt2019'
keywords = ['conferencetalk']
source = '20190620-sunbelt2019'

[talk-12-conference]
entrytype = 'inproceedings'
title = 'Exact Statistics and Semi-Parametric Tests for Small Network Data'
author = 'Vega Yon, George G.; Slaughter, Andrew; de la Haye, Kayla'
year = '2019'
month = '7'
date = '2019-07-19'
eventtitle = 'IC2S2, 2019'
eventurl = 'https://2019.ic2s2.org/'
host = 'University of Amsterdam'
location = 'Amsterdam, NL'
talktype = 'conference talk'
slides = 'https://github.com/gvegayon/ic2s22019/raw/master/index.pdf'
repo = 'https://github.com/gvegayon/ic2s22019'
keywords = ['conferencetalk']
source = '20190719-ic2s22019'

[talk-13-conference]
entrytype = 'inproceedings'
title = 'ERGMito Statistical Models for Small Team Social Networks'
author = 'Vega Yon, George G.; Dinkjian, Aileen; Hamm-Alvarez, Sarah; de la Haye, Kayla'
year = '2020'
month = '6'
date = '2020-06-01'
eventtitle = 'SciTS 2020'
eventurl = 'https://sts.memberclicks.net/scits-2020-home-base'
host = 'International Network for the  Science of Team Science'
location = 'Zoom'
talktype = 'conference talk'
slides = 'https://github.com/gvegayon/talks/raw/master/20200600-scits2020/slides.pdf'
video = 'https://youtu.be/Dg32SnyOO7s'
keywords = ['conferencetalk']
source = '20200600-scits2020'

[talk-14-conference]
entrytype = 'inproceedings'
title = 'Network Influence in Officer Firearm Use'
author = 'Ouellet, Marie; Hashimi, Sadaf; Vega Yon, George G.'
year = '2021'
month = '7'
date = '2021-07-07'
eventtitle = 'NETWORKS 2021 - A Joint Sunbelt and NetSci Conference'
eventurl = 'https://networks2021.net/'
host = 'IU Network Science Institute'
location = 'Online'
talktype = 'conference talk'
keywords = ['conferencetalk']
source = '20210707-networks2021'

[talk-15-conference]
entrytype = 'inproceedings'
title = 'Triads, Dyads, and Gene Functions - When Social Network Analysis Meets Phylogenetics'
author = 'Vega Yon, George G.'
year = '2021'
month = '7'
date = '2021-07-10'
eventtitle = 'NETWORKS 2021 - A Joint Sunbelt and NetSci Conference'
eventurl = 'https://networks2021.net/'
host = 'IU Network Science Institute'
location = 'Online'
talktype = 'conference talk'
keywords = ['conferencetalk']
source = '20210710-networks2021'

[talk-16-conference]
entrytype = 'inproceedings'
title = 'Una Mirada General a los Modelos Cuantitativos de Redes Sociales'
author = 'Vega Yon, George G.'
year = '2021'
month = '11'
date = '2021-11-18'
eventtitle = 'VII Reunión Latinoamericana de Análisis de Redes Sociales'
eventurl = 'https://linea.fcnym.unlp.edu.ar/novedades/vii-reunion-latinoamericana-de-analisis-de-redes-sociales-2/'
host = 'Universidad de La Plata'
location = 'Virtual'
talktype = 'conference talk'
slides = 'https://github.com/gvegayon/ars2021/blob/master/slides.pdf'
repo = 'https://github.com/gvegayon/ars2021'
keywords = ['conferencetalk']
source = '20211118-ars'

[talk-17-conference]
entrytype = 'inproceedings'
title = 'Imaginary Network Motifs: Structural Patterns of False Positives and Negatives in Social Networks'
author = 'Tanaka, Kyosuke; Vega Yon, George G.'
year = '2022'
month = '5'
date = '2022-05-27'
eventtitle = '72th Annual Conference of the International Communication Association'
eventurl = 'https://www.icahdq.org/page/ICA2022'
host = 'ICA'
location = 'Paris, France'
talktype = 'conference talk'
announcement = 'https://mgmt.au.dk/icoa/single/artikel/icoa-researcher-receives-best-paper-award'
keywords = ['conferencetalk']
source = '20220527-ICA2022'

[talk-18-conference]
entrytype = 'inproceedings'
title = 'The importance of interaction networks in long-term care facilities to reduce the equilibrium prevalence of infectious pathogens'
author = 'Samore, Matthew; Vega Yon, George G.; Khader, Karim; Kazemini, Kyle; Chang, Nelson; Visnovsky, Lindsay; Thomas, Alun; Haroldsen, Candace; Stratford, Kristina; Zhang, Chong'
year = '2022'
month = '7'
date = '2022-07-15'
eventtitle = 'Sunbelt 2022'
eventurl = 'https://sunbelt2022.org'
host = 'INSNA'
location = 'Cairns, Australia'
talktype = 'conference talk'
announcement = 'https://whova.com/embedded/session/haKCdMCn9xVRk8P5tBLDKQQJewt60YUrrkpFEcitIlg%3D/2513374/?widget=primary'
keywords = ['conferencetalk']
source = '20220715-sunbelt2022'

[talk-19-conference]
entrytype = 'inproceedings'
title = 'Simulating Complex Agent-Based Model with epiworldR: A fast and flexible ABM framework'
author = 'Vega Yon, George G.; Meyer, Derek'
year = '2023'
month = '6'
date = '2023-06-28'
eventtitle = 'INSNA Sunbelt 2023'
eventurl = 'https://www.insna.org/events/sunbelt-2023'
host = 'INSNA'
location = 'Portland, OR'
talktype = 'conference workshop'
slides = 'https://UofUEpiBio.github.io/epiworldR-workshop'
repo = 'https://github.com/UofUEpiBio/epiworldR-workshop'
announcement = 'https://www.insna.org/events/simulating-complex-agent-based-model-with-epiworldr-a-fast-and-flexible-abm-framework'
keywords = ['conferencetalk']
source = '20230628-sunbelt2023'

[talk-20-conference]
entrytype = 'inproceedings'
title = 'Visualization tools for network science: Building beautiful graphs with netplot'
author = 'Bischoff, Porter; Vega Yon, George G.'
year = '2023'
month = '6'
date = '2023-06-30'
eventtitle = 'INSNA Sunbelt 2023'
eventurl = 'https://www.insna.org/events/sunbelt-2023'
host = 'INSNA'
location = 'Portland, OR'
talktype = 'conference poster'
slides = 'https://UofUEpiBio.github.io/netplot-sunbelt2023'
repo = 'https://github.com/UofUEpiBio/netplot-sunbelt2023'
announcement = 'https://www.insna.org/sunbelt-2023--schedule-of-sessions'
keywords = ['conferencetalk']
source = '20230630-sunbelt2023'

[talk-21-conference]
entrytype = 'inproceedings'
title = 'How Network Structure Affects Epidemiological Indicators in ABMs - A Large Simulation Study Featuring Artificial and Real-world Networks'
author = 'Vega Yon, George G.; Samore, Matthew; Khader, Karim; Zhang, Chong; Thomas, Alun'
year = '2023'
month = '7'
date = '2023-07-01'
eventtitle = 'INSNA Sunbelt 2023'
eventurl = 'https://www.insna.org/events/sunbelt-2023'
host = 'INSNA'
location = 'Portland, OR'
talktype = 'conference talk'
slides = 'https://ggv.cl/slides/sunbelt2023'
repo = 'https://uofuepibio.github.io/abm-networks-epi'
announcement = 'https://www.insna.org/sunbelt-2023--schedule-of-sessions'
keywords = ['conferencetalk']
source = '20230721-sunbelt2023'

[talk-22-conference]
entrytype = 'inproceedings'
title = 'epiworld: A fast multi-language library for epi ABMs'
author = 'Vega Yon, George G.; Meyer, Derek; Banks, Milo; Samore, Matthew'
year = '2024'
month = '9'
date = '2024-09-03'
eventtitle = 'Conference on Complex Systems, 2024'
eventurl = 'https://ccs24.cssociety.org'
host = 'Complex Systems Society'
location = 'Exeter, UK'
talktype = 'conference talk'
slides = 'https://ggv.cl/slides/ccs2024'
repo = 'https://github.com/gvegayon/ccs2024'
keywords = ['conferencetalk']
source = '20240903-ccs2024'

[talk-23-conference]
entrytype = 'inproceedings'
title = 'How does network structure in Agent-Based Models affect epidemiological parameters? A large simulation study'
author = 'Olivera, Aníbal; Vega Yon, George G.; Zhang, Chong; Thomas, Alun; Samore, Matthew; Khader, Karim'
year = '2024'
month = '10'
date = '2024-10-27'
eventtitle = 'CSS 2024 Santa Fe'
eventurl = 'https://computationalsocialscience.org/conferences/css-2024-santa-fe/'
host = 'Computational Social Science Society of the Americas'
location = 'Santa Fe, NM'
talktype = 'conference poster'
slides = 'https://drive.google.com/file/d/10s43WsqoXXCqOwgC92tH1ddXDe76xal0/view'
repo = 'https://drive.google.com/file/d/10s43WsqoXXCqOwgC92tH1ddXDe76xal0/view'
announcement = 'http://computationalsocialscience.org/wp-content/uploads/2024/10/CSS2024ConferenceSchedule_Final.docx.pdf'
keywords = ['conferencetalk']
source = '20241027-css-americas'

[talk-24-conference]
entrytype = 'inproceedings'
title = 'Automatic Calibration of Agent-Based Models using Deep Neural Networks'
author = 'Najafzadehkhoei, Sima; Vega Yon, George G.'
year = '2024'
month = '11'
date = '2024-11-01'
eventtitle = 'DELPHI Symposium 2024'
eventurl = 'https://lu.ma/DELPHI'
host = 'DELPHI'
location = 'Salt Lake City, UT'
talktype = 'conference poster'
slides = 'https://drive.google.com/drive/u/0/folders/1FJRKJb5oDQjftnf7Ifo27GbIcjDqPou7'
repo = 'https://drive.google.com/drive/u/0/folders/1FJRKJb5oDQjftnf7Ifo27GbIcjDqPou7'
announcement = 'https://uofuhealth.utah.edu/delphi-symposium'
keywords = ['conferencetalk']
source = '20241101-delphi'

[talk-25-conference]
entrytype = 'inproceedings'
title = 'Expanding the ERGM Framework: Modeling Interrelated Health Outcomes with Jointly-Distributed Binary Data'
author = 'Vega Yon, George G.; Valente, Thomas W.; Kean, Jacob; Pugh, Mary Jo'
year = '2025'
month = '6'
date = '2025-06-26'
eventtitle = 'Sunbelt Conference, 2025'
host = 'INSNA'
location = 'Paris, France'
talktype = 'conference talk'
slides = 'https://uofuepibio.github.io/defm-sunbelt2025'
repo = 'https://github.com/UofUEpiBio/defm-sunbelt2025'
announcement = 'https://sunbelt2025.org/workshops/#toggle-id-55'
keywords = ['conferencetalk']
source = '20250626-sunbelt2025-defm'

[talk-26-conference]
entrytype = 'inproceedings'
title = 'Understanding Diffusion with netdiffuseR'
author = 'Vega Yon, George G.; Olivera, Anival; Valente, Thomas W.'
year = '2025'
month = '6'
date = '2025-06-24'
eventtitle = 'Sunbelt Conference, 2025'
host = 'INSNA'
location = 'Paris, France'
talktype = 'conference workshop'
slides = 'https://github.com/USCCANA/netdiffuser-workshop'
repo = 'https://github.com/USCCANA/netdiffuser-workshop'
announcement = 'https://sunbelt2025.org/workshops/#toggle-id-55'
keywords = ['conferencetalk']
source = '20250626-sunbelt2025-netdiffuseR'

[talk-27-conference]
entrytype = 'inproceedings'
title = 'Artificial Intelligence for the Scientist in a Hurry'
author = 'Vega Yon, George G.'
year = '2026'
month = '6'
date = '2026-06-23'
eventtitle = 'Sunbelt Conference, 2026'
eventurl = 'https://www.insna.org/events/sunbelt-2026---daytona-beach'
host = 'INSNA'
location = 'Daytona Beach, Florida, USA'
talktype = 'conference workshop'
slides = 'https://docs.google.com/presentation/d/14CRTzeyNbtMEPnOVolM8SRFrJ07JLoWThoMZVao3WFo/edit?usp=sharing'
announcement = 'https://www.insna.org/events/sunbelt-2026---daytona-beach#workshopinformation'
keywords = ['conferencetalk']
source = '20260623-sunbelt2026-ai'

[talk-28-conference]
entrytype = 'inproceedings'
title = 'Understanding Diffusion with netdiffuseR'
author = 'Vega Yon, George G.; Olivera, Anival; Valente, Thomas W.'
year = '2026'
month = '6'
date = '2026-06-24'
eventtitle = 'Sunbelt Conference, 2026'
eventurl = 'https://www.insna.org/events/sunbelt-2026---daytona-beach'
host = 'INSNA'
location = 'Daytona Beach, Florida, USA'
talktype = 'conference workshop'
slides = 'https://github.com/USCCANA/netdiffuser-workshop'
repo = 'https://github.com/USCCANA/netdiffuser-workshop'
announcement = 'https://www.insna.org/events/sunbelt-2026---daytona-beach#workshopinformation'
keywords = ['conferencetalk']
source = '20260624-sunbelt2026-netdiffuseR'

[talk-29-conference]
entrytype = 'inproceedings'
title = 'Variability of ERGM fits influences epidemic simulation results: A case study of Monkeypox virus transmission and methods for robust scenario analysis'
author = 'Rosenblatt, Samuel; Manuelpillai, Bevin; Spicknall, Ian; Miller, Paige; Vega Yon, George G.; Clay, Patrick; Mistry, Dina; Pollock, Emily'
year = '2026'
month = '6'
eventtitle = 'Sunbelt Conference, 2026'
talktype = 'conference talk'
keywords = ['conferencetalk']
