[talk-1-invited]
entrytype = 'inproceedings'
title = 'Estadística de Redes y Econometría Espacial (con R)'
author = ''
year = '2018'
month = '12'
eventtitle = 'IMFD Summer School'
note = '(invited talk, [slides](https://github.com/gvegayon/redes-estadisticas2018)/[video](https://www.facebook.com/Fundamentosdelosdatos/videos/281299225908470/))'
keywords = ['invitedtalk']

[talk-2-invited]
entrytype = 'inproceedings'
title = 'Big Problems for Small Networks: Statistical Analysis of Small Networks and Team Performance'
author = ''
year = '2019'
month = '3'
eventtitle = 'SONIC Speaker'
note = '(invited talk, [slides](https://github.com/gvegayon/nu2019/raw/nu03-2019/talk/ggvy-nu2019-talk-handout.pdf)/[video](https://youtu.be/0eTqv5cxTwU))'
keywords = ['invitedtalk']

[talk-3-invited]
entrytype = 'inproceedings'
title = 'Big Problems for Small Networks: Statistical Analysis of Small Networks and Team Performance'
author = ''
year = '2019'
month = '4'
eventtitle = 'UCI Social Network Research Group'
note = '(invited talk, [slides](https://github.com/gvegayon/nu2019/raw/uci2019/talk/ggvy-uci2019-talk-handout.pdf))'
keywords = ['invitedtalk']

[talk-4-invited]
entrytype = 'inproceedings'
title = 'A Brief Introduction to Using R for High-Performance Computing'
author = ''
year = '2019'
month = '8'
eventtitle = 'Orange County R Users Group'
note = '(invited talk, [slides](https://gvegayon.github.io/ocrug-hpc-august2019)/[video](https://youtu.be/gLmEBINxbFE))'
keywords = ['invitedtalk']

[talk-5-invited]
entrytype = 'inproceedings'
title = 'Predicción de funciones genéticas utilizando evidencia experimental y árboles filogenéticos: Un modelo evolutivo" o "Ciencia de datos en la práctica'
author = ''
year = '2020'
month = '4'
eventtitle = 'PUC Mathematical and Computational Engineering Seminars'
note = '(invited talk, [slides](https://github.com/gvegayon/charla-puc-abril2020/blob/master/slides.pdf))'
keywords = ['invitedtalk']

[talk-6-invited]
entrytype = 'inproceedings'
title = 'Triads, Dyads, and Gene Functions - When Social Network Analysis Meets Phylogenetics'
author = ''
year = '2021'
month = '3'
eventtitle = 'Computational Cancer Genomics Working Group Evening Lecture'
note = '(invited talk, [slides](https://ggv.cl/slides/nygc)/[video](https://youtu.be/LEHu_ciVb5A))'
keywords = ['invitedtalk']

[talk-7-invited]
entrytype = 'inproceedings'
title = 'Triadas, lazos y funciones genéticas: cuando las redes sociales y la filogenética se encuentran'
author = ''
year = '2021'
month = '5'
eventtitle = 'Seminario de Data Science'
note = '(invited talk, [slides](https://ggv.cl/slides/uai-ds )/[video](https://youtu.be/WrJgffkKTzQ))'
keywords = ['invitedtalk']

[talk-8-invited]
entrytype = 'inproceedings'
title = 'Prediction of Gene Functions by Leveraging Biological Insights with Mechanistic Machine Learning'
author = ''
year = '2023'
month = '1'
eventtitle = 'University of Utah Data Science Seminar'
note = '(invited talk, [slides](https://github.com/gvegayon/talks/tree/master/20230111-uofu-datascience)/[video](https://www.youtube.com/watch?v=c9ozeJHNAc4))'
keywords = ['invitedtalk']

[talk-9-invited]
entrytype = 'inproceedings'
title = 'Network visualization (in R) with “netplot” and motif counting (in C++) with “barry”'
author = ''
year = '2023'
month = '4'
eventtitle = 'SCI Seminar'
note = '(invited talk, [slides](https://gvegayon.github.io/sci2023/))'
keywords = ['invitedtalk']

[talk-10-invited]
entrytype = 'inproceedings'
title = 'Power and multicollinearity in small networks: A discussion of “Tale of Two Datasets: Representativeness and Generalisability of Inference for Samples of Networks” by Krivitsky, Coletti & Hens'
author = ''
year = '2023'
month = '8'
eventtitle = 'Joint Statistical Meetings, 2023'
note = '(invited talk, [slides](https://gvegayon.github.io/jsm-discussion))'
keywords = ['invitedtalk']

[talk-11-invited]
entrytype = 'inproceedings'
title = 'What is a Scientist?'
author = ''
year = '2023'
month = '11'
eventtitle = 'Career Day 2023'
note = '(invited talk, [slides](https://docs.google.com/presentation/d/160HTOw9O79njLeI2kt36rNmeLHRpRYko7161p7MU7wM/edit?usp=sharing))'
keywords = ['invitedtalk']

[talk-12-invited]
entrytype = 'inproceedings'
title = "'La Muerte del Aprendizaje de Máquina' o 'cómo la teoría puede mejorar a las máquinas'"
author = ''
year = '2024'
month = '1'
eventtitle = 'Escuela de Verano de Sistemas Complejos'
note = '(invited talk, [slides](https://gvegayon.github.io/mechml-udd-ene2024/))'
keywords = ['invitedtalk']

[talk-13-invited]
entrytype = 'inproceedings'
title = 'Exponential Random Graph Models: An Introduction'
author = ''
year = '2024'
month = '7'
eventtitle = 'Summer Institute in Computational Social Science'
note = '(invited talk, [slides](https://gvegayon.github.io/sicss-uof-2024/))'
keywords = ['invitedtalk']

[talk-14-invited]
entrytype = 'inproceedings'
title = 'Machine Learning Sandwich for Agent-Based Models: Automatic calibration and post-processing adjustment for ABMs'
author = ''
year = '2024'
month = '9'
eventtitle = 'Methods talks'
note = '(invited talk, [slides](https://ggvy.cl/slides/exeter-abm-2024))'
keywords = ['invitedtalk']

[talk-15-invited]
entrytype = 'inproceedings'
title = 'A Brief Introduction to High-Performance Computing: With Applications in R'
author = ''
year = '2024'
month = '9'
eventtitle = 'Methods talks'
note = '(invited talk, [slides](https://ggvy.cl/slides/exeter-hpc-2024))'
keywords = ['invitedtalk']

[talk-16-invited]
entrytype = 'inproceedings'
title = 'Artificial Intelligence for the Scientist in a Hurry'
author = ''
year = '2026'
month = '6'
eventtitle = 'Summer Institute in Computational Social Science (SICSS-UF)'
note = '(invited talk, [slides](https://docs.google.com/presentation/d/11VwH8437yyqLY4mcrYKPMXY7makPwE8uX4QXCvJUBII/edit?usp=sharing))'
keywords = ['invitedtalk']

[talk-17-invited]
entrytype = 'inproceedings'
title = 'How can models help public health?: Reflections from a Modeler'
author = ''
year = '2026'
eventtitle = 'Epi Corner'
note = '(invited talk, [slides](https://docs.google.com/presentation/d/1tRYpRmqojL2exDZ4q494TobGHJgBJ4igmiWvZbkRKbk/edit?usp=sharing))'
keywords = ['invitedtalk']

