[talk-1-invited]
entrytype = 'inproceedings'
title = 'Estadística de Redes y Econometría Espacial (con R)'
author = 'Vega Yon, George G.'
year = '2018'
month = '12'
date = '2018-12-20'
eventtitle = 'IMFD Summer School'
host = 'Instituto Milenio Fundamento de los datos'
location = 'Santiago, Chile'
talktype = 'invited talk'
slides = 'https://github.com/gvegayon/redes-estadisticas2018'
video = 'https://www.facebook.com/Fundamentosdelosdatos/videos/281299225908470/'
repo = 'https://github.com/gvegayon/redes-estadisticas2018'
announcement = 'https://imfd.cl/agenda_evento/escuela-de-analisis-de-datos-en-r-tutorial-1-george-vega-yon/'
keywords = ['invitedtalk']
source = '20190102-redes-estadisticas'

[talk-2-invited]
entrytype = 'inproceedings'
title = 'Big Problems for Small Networks: Statistical Analysis of Small Networks and Team Performance'
author = 'Vega Yon, George G.; de la Haye, Kayla'
year = '2019'
month = '3'
date = '2019-03-20'
eventtitle = 'SONIC Speaker'
host = 'Northwestern University'
location = 'Evanston, IL'
talktype = 'invited talk'
slides = 'https://github.com/gvegayon/nu2019/raw/nu03-2019/talk/ggvy-nu2019-talk-handout.pdf'
video = 'https://youtu.be/0eTqv5cxTwU'
repo = 'https://github.com/gvegayon/nu2019/tree/nu03-2019'
announcement = 'http://sonic.northwestern.edu/sonic-speaker-series-presents-george-g-vega-yon/'
keywords = ['invitedtalk']
source = '20190320-nu'

[talk-3-invited]
entrytype = 'inproceedings'
title = 'Big Problems for Small Networks: Statistical Analysis of Small Networks and Team Performance'
author = 'Vega Yon, George G.; de la Haye, Kayla'
year = '2019'
month = '4'
date = '2019-04-29'
eventtitle = 'UCI Social Network Research Group'
host = 'University of California Irvine'
location = 'Irvine, CA'
talktype = 'invited talk'
slides = 'https://github.com/gvegayon/nu2019/raw/uci2019/talk/ggvy-uci2019-talk-handout.pdf'
repo = 'https://github.com/gvegayon/nu2019/tree/uci2019'
announcement = 'https://maillists.uci.edu/pipermail/snrlist-announce/2019-April/000329.html'
keywords = ['invitedtalk']
source = '20190429-uci'

[talk-4-invited]
entrytype = 'inproceedings'
title = 'A Brief Introduction to Using R for High-Performance Computing'
author = 'Vega Yon, George G.'
year = '2019'
month = '8'
date = '2019-08-27'
eventtitle = 'Orange County R Users Group'
host = 'Orange County R Users Group'
location = 'Irvine, CA'
talktype = 'invited talk'
slides = 'https://gvegayon.github.io/ocrug-hpc-august2019'
video = 'https://youtu.be/gLmEBINxbFE'
repo = 'https://github.com/gvegayon/ocrug-hpc-august2019'
announcement = 'https://ocrug.org/blog/2019/08/27/2019-08-27-advanced-regressions-and-high-performance-computing/'
keywords = ['invitedtalk']
source = '20190827-ocrug-pll'

[talk-5-invited]
entrytype = 'inproceedings'
title = 'Predicción de funciones genéticas utilizando evidencia experimental y árboles filogenéticos: Un modelo evolutivo" o "Ciencia de datos en la práctica'
author = 'Vega Yon, George G.'
year = '2020'
month = '4'
date = '2020-04-15'
eventtitle = 'PUC Mathematical and Computational Engineering Seminars'
host = 'PUC'
location = 'Zoom'
talktype = 'invited talk'
slides = 'https://github.com/gvegayon/charla-puc-abril2020/blob/master/slides.pdf'
repo = 'https://github.com/gvegayon/charla-puc-abril2020'
announcement = 'http://mat.puc.cl/seminarios?lang=en'
keywords = ['invitedtalk']
source = '20200400-charla-puc'

[talk-6-invited]
entrytype = 'inproceedings'
title = 'Triads, Dyads, and Gene Functions - When Social Network Analysis Meets Phylogenetics'
author = 'Vega Yon, George G.'
year = '2021'
month = '3'
date = '2021-03-09'
eventtitle = 'Computational Cancer Genomics Working Group Evening Lecture'
eventurl = 'https://www.nygenome.org/event/computational-cancer-genomics-working-group-evening-lecture-5/'
host = 'NY Genome Center'
location = 'Zoom'
talktype = 'invited talk'
slides = 'https://ggv.cl/slides/nygc'
video = 'https://youtu.be/LEHu_ciVb5A'
repo = 'https://github.com/gvegayon/ny-genome-talk'
keywords = ['invitedtalk']
source = '20210309-nygc'

[talk-7-invited]
entrytype = 'inproceedings'
title = 'Triadas, lazos y funciones genéticas: cuando las redes sociales y la filogenética se encuentran'
author = 'Vega Yon, George G.'
year = '2021'
month = '5'
date = '2021-05-19'
eventtitle = 'Seminario de Data Science'
eventurl = 'https://noticias.uai.cl/evento/triadas-lazos-y-funciones-geneticas-cuando-las-redes-sociales-y-la-filogenetica-se-encuentran/?utm_source=BaseInterna&utm_medium=email&utm_campaign=AgendaComunicaciones&utm_term=Interna17mayo2021'
host = 'Universidad Adolfo Ibáñez'
location = 'Zoom'
talktype = 'invited talk'
slides = 'https://ggv.cl/slides/uai-ds'
video = 'https://youtu.be/WrJgffkKTzQ'
keywords = ['invitedtalk']
source = '20210519-uai-ds'

[talk-8-invited]
entrytype = 'inproceedings'
title = 'Prediction of Gene Functions by Leveraging Biological Insights with Mechanistic Machine Learning'
author = 'Vega Yon, George G.'
year = '2023'
month = '1'
date = '2023-01-11'
eventtitle = 'University of Utah Data Science Seminar'
host = 'ICA'
location = 'Salt Lake City, Utah'
talktype = 'invited talk'
slides = 'https://github.com/gvegayon/talks/tree/master/20230111-uofu-datascience'
video = 'https://www.youtube.com/watch?v=c9ozeJHNAc4'
repo = 'https://github.com/gvegayon/geese-talk-quinlanlab/tree/uoudstalk202301'
announcement = 'https://www.google.com/calendar/event?eid=XzcwbzNlZDIyNjBxMzBiOWw3MG9qZWI5azc1MmpnYmEyNjRvazZiYTQ2b3MzNmdhNjhwMTMwYzIxNjggZWtvbDd1bHFtMTRudjE1NWFuZ3V0MnJsZm9AZw'
keywords = ['invitedtalk']
source = '20230111-uofu-datascience'

[talk-9-invited]
entrytype = 'inproceedings'
title = 'Network visualization (in R) with “netplot” and motif counting (in C++) with “barry”'
author = 'Vega Yon, George G.'
year = '2023'
month = '4'
date = '2023-04-07'
eventtitle = 'SCI Seminar'
host = 'Scientific Computing and Imaging Institute'
location = 'Salt Lake City, Utah'
talktype = 'invited talk'
slides = 'https://gvegayon.github.io/sci2023/'
repo = 'https://github.com/gvegayon/sci2023'
announcement = 'https://www.sci.utah.edu/component/events/day/20230407.html'
keywords = ['invitedtalk']
source = '20230407-sci-utah'

[talk-10-invited]
entrytype = 'inproceedings'
title = 'Power and multicollinearity in small networks: A discussion of “Tale of Two Datasets: Representativeness and Generalisability of Inference for Samples of Networks” by Krivitsky, Coletti & Hens'
author = 'Vega Yon, George G.'
year = '2023'
month = '8'
date = '2023-08-09'
eventtitle = 'Joint Statistical Meetings, 2023'
eventurl = 'https://ww2.amstat.org/meetings/jsm/2023/'
host = 'American Statistical Association'
location = 'Toronto, Canada'
talktype = 'invited talk'
slides = 'https://gvegayon.github.io/jsm-discussion'
repo = 'https://github.com/gvegayon/jsm-discussion'
announcement = 'https://ww2.aievolution.com/JSMAnnual/index.cfm?do=ev.viewEv&ev=1277'
keywords = ['invitedtalk']
source = '20230809-jsm2023'

[talk-11-invited]
entrytype = 'inproceedings'
title = 'What is a Scientist?'
author = 'Vega Yon, George G.'
year = '2023'
month = '11'
date = '2023-11-21'
eventtitle = 'Career Day 2023'
host = 'Altara Elementary School'
location = 'Sandy, UT'
talktype = 'invited talk'
slides = 'https://docs.google.com/presentation/d/160HTOw9O79njLeI2kt36rNmeLHRpRYko7161p7MU7wM/edit?usp=sharing'
keywords = ['invitedtalk']
source = '20231121-career-day-altara'

[talk-12-invited]
entrytype = 'inproceedings'
title = "'La Muerte del Aprendizaje de Máquina' o 'cómo la teoría puede mejorar a las máquinas'"
author = 'Vega Yon, George G.'
year = '2024'
month = '1'
date = '2024-01-15'
eventtitle = 'Escuela de Verano de Sistemas Complejos'
host = 'Universidad del Desarrollo'
location = 'Santiago, Chile'
talktype = 'invited talk'
slides = 'https://gvegayon.github.io/mechml-udd-ene2024/'
repo = 'https://github.com/gvegayon/mechml-udd-ene2024'
keywords = ['invitedtalk']
source = '20240115-mechml-udd'

[talk-13-invited]
entrytype = 'inproceedings'
title = 'Exponential Random Graph Models: An Introduction'
author = 'Vega Yon, George G.'
year = '2024'
month = '7'
date = '2024-07-04'
eventtitle = 'Summer Institute in Computational Social Science'
eventurl = 'https://sicss.io/2024/florida/'
host = 'The University of Florida'
location = 'Florida, USA'
talktype = 'invited talk'
slides = 'https://gvegayon.github.io/sicss-uof-2024/'
repo = 'https://github.com/gvegayon/sicss-uof-2024'
keywords = ['invitedtalk']
source = '20240704-sicss-florida'

[talk-14-invited]
entrytype = 'inproceedings'
title = 'Machine Learning Sandwich for Agent-Based Models: Automatic calibration and post-processing adjustment for ABMs'
author = 'Vega Yon, George G.'
year = '2024'
month = '9'
date = '2024-09-04'
eventtitle = 'Methods talks'
host = 'The University of Exeter'
location = 'Exeter, UK'
talktype = 'invited talk'
slides = 'https://ggvy.cl/slides/exeter-abm-2024'
repo = 'https://github.com/gvegayon/exeter-abms-sep2024'
keywords = ['invitedtalk']
source = '20240904-abm-exeter'

[talk-15-invited]
entrytype = 'inproceedings'
title = 'A Brief Introduction to High-Performance Computing: With Applications in R'
author = 'Vega Yon, George G.'
year = '2024'
month = '9'
date = '2024-09-04'
eventtitle = 'Methods talks'
host = 'The University of Exeter'
location = 'Exeter, UK'
talktype = 'invited talk'
slides = 'https://ggvy.cl/slides/exeter-hpc-2024'
repo = 'https://github.com/gvegayon/exeter-hpc-sep2024'
keywords = ['invitedtalk']
source = '20240904-hpc-exeter'

[talk-16-invited]
entrytype = 'inproceedings'
title = 'Artificial Intelligence for the Scientist in a Hurry'
author = 'Vega Yon, George G.'
year = '2026'
month = '6'
date = '2026-06-19'
eventtitle = 'Summer Institute in Computational Social Science (SICSS-UF)'
eventurl = 'https://sicss.io/2026/uf/'
host = 'INSNA'
location = 'Gainesville, Florida, USA'
talktype = 'invited talk'
slides = 'https://docs.google.com/presentation/d/11VwH8437yyqLY4mcrYKPMXY7makPwE8uX4QXCvJUBII/edit?usp=sharing'
keywords = ['invitedtalk']
source = '20260619-sicss-ai'

[talk-17-invited]
entrytype = 'inproceedings'
title = 'How can models help public health?: Reflections from a Modeler'
author = 'Vega Yon, George G.'
year = '2026'
month = '4'
eventtitle = 'Epi Corner'
talktype = 'invited talk'
slides = 'https://docs.google.com/presentation/d/1tRYpRmqojL2exDZ4q494TobGHJgBJ4igmiWvZbkRKbk/edit?usp=sharing'
keywords = ['invitedtalk']

[talk-18-invited]
entrytype = 'inproceedings'
title = 'From Supercomputers to Health Departments'
author = 'Vega Yon, George G.'
year = '2026'
month = '9'
eventtitle = 'Network Science Institute + Roux Institute'
talktype = 'invited talk'
slides = 'https://gvegayon.github.io/nsi-sep2026'
announcement = 'https://www.networkscienceinstitute.org/talks/george-vega-yons'
keywords = ['invitedtalk']
