FROM ghcr.io/rocker-org/devcontainer/r-ver:4.5

# Architecture-specific variable (built in Docker BuildKit)
ARG TARGETARCH

# Install quarto-cli and the orange-book extension
RUN wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.10.18/quarto-1.10.18-linux-${TARGETARCH}.deb && \
    dpkg -i quarto-1.10.18-linux-${TARGETARCH}.deb && \
    rm quarto-1.10.18-linux-${TARGETARCH}.deb

CMD ["bash"]
