project:
  type: website
  output-dir: ../public/zh
  render: 
    - "*.qmd"

  resources:
    - "../img/"

website:
  title: "George G. Vega Yon, Ph.D."
  image: ../img/logo.svg
  search: false
  description: |
    George G. Vega Yon 博士的個人網站，猶他大學數據科學助理教授。Vega Yon 博士從事統計計算、數據科學和科學軟件開發工作。
  navbar:
    logo: ../img/logo.svg
    background: "#ff8000ff"
    foreground: white
    collapse-below: lg
    left:
      - href: index.qmd
        text: 主頁
      - href: research.qmd
        text: 研究
      - href: software.qmd
        text: 軟件
      - href: talks.qmd
        text: 演講
      - href: teaching.qmd
        text: 教學
      - text: '簡歷'
        menu:
          - text: Resume (簡要)
            href: https://raw.githubusercontent.com/gvegayon/resume/master/resume.pdf
          - text: CV (學術)
            href: https://raw.githubusercontent.com/gvegayon/resume/master/cv.pdf
    right:
      - href: ../index.html
        text: 🇺🇸
      - href: ../es/index.html
        text: 🇪🇸
      - href: https://github.com/gvegayon
        icon: github
      - href: https://linkedin.com/in/georgevegayon
        icon: linkedin
      - href: https://scholar.google.com/citations?user=34E1yTAAAAAJ&hl=en
        icon: mortarboard-fill
      - href: https://bsky.app/profile/gvegayon.bsky.social
        icon: bluesky
      - href: https://orcid.org/0000-0002-3171-0844
        text: ORCID
  google-analytics: G-FH7BRCRDTQ

  page-footer:
    center: |
      © 2025 George G. Vega Yon. 版權所有。

format:
  html:
    theme: 
      - default
    css: ../styles.css
    toc: false
    page-layout: article

execute:
  freeze: false
